module.exports = {
    selfIntroduction: ["nei5", "hou2", "ngo5", "giu3", "nome", "gou1", "hing3", "jing6", "sik1", "dou1", "hai6", "sing3"],
    country: ["Eu sou", "pessoa", "China", "Portugal", "EUA", "Espanha", "França", "Alemanha", "Itália", "Japão", "Coreia do Sul", "Tailândia"],
    cardinalDirection: ["Norte", "Sul", "Este", "Oeste"],
    classroom: ["Cantonês", "Como dizer", "Obrigado", "Mais devagar", "Ajudar", "Escrever"],
    wordOfTheDay: ["hang4 lei5 soeng1 (Suitcase)", "leon4 geoi1 (Neighboor)", "caan1 coek3 (table)", "din6 si6 (TV)"],
    expressions: ["ceong4 gau2 (long time)", "noi6/gau2 (long time no see)", "but1 gwo3 (but)", "bat1 jung6 haak3 hei3 (you're welcome)"],
    colors: ["hung4", "baak6"],
    characters: ["Nome (Self-Intoduction)", "sing3 (Self-Intoduction)", "hou2 (Self-Intoduction)", "nei5 (Self-Intoduction)", "jing6 (Self-Intoduction)", "sik1 (Self-Intoduction)", 
    "gou1 (Self-Intoduction)", "hing3 (Self-Intoduction)", "dou1 (Self-Intoduction)", "hai6 (Self-Intoduction)", "giu3 (Self-Intoduction)", "ngo5 (Self-Intoduction)", 
    "jan4 (Nationality)", "zung1 (Nationality)", "gwok3 (Nationality)", "mei5 (Nationality)", "pou4 (Nationality)", "tou4 (Nationality)", "nga4 (Nationality)", "faat3 (Nationality)", 
    "dak1 (Nationality)", "ji3 (Nationality)", "daai6 (Nationality)", "lei5 (Nationality)", "baan1 (Nationality)", "jat6 (Nationality)", "bun2 (Nationality)", 
    "hon4 (Nationality)", "taai3 (Nationality)", "jing1 (Nationality)", "man2 (Country language)"],
    characters2: ["ling4 (Numbers)", "jat1 (Numbers)", "ji6 (Numbers)", "saam1 (Numbers)", "sei3 (Numbers)", "ng5 (Numbers)", 
    "luk6 (Numbers)", "cat1 (Numbers)", "baat3 (Numbers)", "gau2 (Numbers)", "sap6 (Numbers)", "baak3 (Numbers)", "cin3 (Numbers)", "maan6 (Numbers)", "dung1 (Cardinal Direction)", 
    "naam4 (Cardinal Direction)", "sai1 (Cardinal Direction)", "bak1 (Cardinal Direction)", "gwong2 (Classroom)", "waa2 (Classroom)", "dim2 (Classroom)", 
    "gong2 (Classroom)", "m4 (Classroom)", "goi1 (Classroom)", "maan6 (Classroom)", "di1 (Classroom)", "bong1 (Classroom)", "se2 (Classroom)", "dai1 (Classroom)",
    "hang4 (For Travelling)", "lei5 (For Travelling)", "soeng1 (For Travelling)", "leon4 (Next Door)", "geoi1 (Next Door)", "caan1 (Table)", "coek3 (Table)", "ge3 (Possession)",
    "din6 (eletricity)", "si (tv)"],
    characters3: ["sing1 kei4/lai5 baai3 (week)", "gam1 (day)", "tin1 (day)", "ming4 (day)", "zok3 (day)", "soeng2 jiu3 (want)", "man6 tai4 (problem)",
    "gei2 do1 (how much)", "leng3 (beautiful)", "junng6 (use)", "zou6 (do)", "seoi2 (drink)", "fo2 (hot)", "mok3 (knock-knock)", "jyut6 (calendar)", "nin4 (calendar)", 
    "siu2 (not many)", "be1 (alchool)", "zau2 (alchool)", "ni1 (here)", "dou6 (here)", "jau (have)", "mou5 (not have)", "aa3 (question)", "taa1 (he/she/it)", 
    "dei6 (plural pronoun)", "ze2 (lady)", "zi1 zeon1 (one bottle)", "sik6/hek3 (food)", "jam2 (drinks)", "miu5 (time)", "si4 (time)", "fan1 (time)", 
    "zung1 (time)", "me1 (what?)", "ho2 ji5 (can)", "bui1 (glass)", "pang4 jau5 (friend)", "neoi5 (girl)", "naam4 (guy)",
    "m4 hou2 ji3 si1 (excuse me)", "dak1 m4 dak1 haan4 (are you free?)"],
    characters4: ["bat1 (no)", "soeng5 (up)", "haa6 (down)", "taai3 (too)", "hoi1 (open)", "san1 (close)", "sau1 (leave)", "gung1 zok3 (work)", 
    "zo2 (-ed)", "ho2 m4 ho4 ji5 (can you)", "coeng3 (sing)", "jyu4 gwo2 (if)", "jyu5 jin4 (languages)", "teng1 (hear)", "sau2 (hand)", 
    "sam1 (heart)", "hok6 (learn)", "oi3 nei5 (love you)", "tung4 (with)", "gin3/hon3/tai2 (seen)", "ceaong4 (length)", "dyun2 (length)", 
    "saan1 (mountain)", "fu6 can1 (father)", "mou5 can1 (mother)", "tou2 dei6 (land)", "zi2 (child)", "ng5 on1 (good afternoon)", "mun4 (door)", "cau3/man4 (smell)",
    "zo2 (left)", "jau6 (right)", "ji5 (ear)", "hau2 (mouth)", "ngaan5 (eye)", "bei6 (nose)", "sam1 lam4 (forest)", "lik6 loeng6 (strength)"],
    characters5: [ "san1 man4 (news)", "jan4 man4 (people of a country)", "lap6 (vertical/stand)", "bun3 (half)", "ngoi6 (foreign)",
    "zai2 (son)", "neoi5 (daughter)", "sang1 (birth)", "baak6 (white/clean)", "ceot1 (leave)", "zou2 san4 (good morning)", "zou2 tau2 (good night sleep)", 
    "maan5 on1 (good evening/night)", "sin1 (first/in advance)", "on1 (peaceful)", "meng2 (nome)", "wo4 ping4 (peace)", "zi6 (letter)", 
    "jan1 wai6 (because)", "mui5 (every/each)"],
    characters6: ["ce1 (car)", "faa1 (flower)", "se5 wui2 (society)", "gam1 (gold)", "hoi2 joeng4 (ocean)", "hoi2 (sea)", "ho4 (river)",
    "jyu5 (rain)", "tin1 hung1 (sky)", "hung1 (empty)", "fu6 gan6/kan6 (near)", "bei2/kap1 (give)", "dim3 (store)", "cin4 (front)", "hau6 (back)",
    "haau6 (school)", "jyu4 (fish)", "juk6 (meat)", "gai1 (chicken)", "zyu1 (pork)", "ngau4 (cow)", "hak1 (black)", "maai5/maai6 (buy/sell)", "san1 (new)",
    "gaa3 fe1 (coffe)", "caa4 (tea)", "mai5/faan6 (rice)", "loi4/lei4 zi6 (from)", "zyu6 (live)", "jam1 ngok6 (music)", "syu1 (book)",
    "gei1 hei3 (machine)", "seoi3 (age)", "gau6 (object old)", "sik1 dou2 (did meet)", "ngaan4 sik1 (color)", "hung4 zau2 (red whine)"],
    characters7: ["si1 gei1 (driver)", "hoi2/saa1 taan1 (beach)", "gan2 (-ing)", "gwo2 zap1 (juice)", "dung3 ding6 jit6 (cold or hot)",
    "ngaa5/zi2 bui1 (mug/paper cup)", "do1 ze6 (thank you)", "zung6 (still)", "jing2 soeng2 (take a picture)", "cing2 man6 (may i ask)",
    "daai6/sai3 (big/small)", "dai6 ji2 zek3 (another one)", "fong3 hok6 (leave school)", "ma4 ma4 dei6 (more or less)",
    "ci4 di1 gin3 (see you later)", "baai3/zoi3 gin (bye)", "zuk1 nei5 hou2 wan6 (good luck)", "faai3 (quick)", "ceong4 gau2 (long time)",
    "noi6/gau2 (long time no see)", "but1 gwo3 (but)", "m4 sai2/bat1 jung6 haak3 hei3 (you're welcome)"
    // "hing3 ceoi3/si3 hou3 (hobby)", "goek3 (foot)", "teoi2 (leg)", "tau4 (head)", "sau2 bei3 (arm)", "sau2 zi2 (finger)",
    // "san1 tai2 (body)", "tou5 (stomach)", "bui3 zek3 (back)", "hung1 (chest)"
    ],
    characters8: ["jat1 gaa1 jan4 (family)", "maa4 maa1/baa4 baa1 (mother/father)", "lou5 po4/lou5 gung1 (wife/husband)", "gaa1 zoeng2 (parent)",
    "sai3 lou6 (child)", "zi2 mui2 (sister)", "go4 go1 (brother)", "mui4 mui2 (sister)", "sai3 lou2 (little brother)", "po4 po2 (grandmother)",
    "ji4 maa1/suk1 suk1 (aunt/uncle)", "taai3 maa4/taai3 gung1 (great-grandmother/father)", "je4 je2/gung4 gung1 (grandfather)",
    "syun1 neoi5 (granddaughter)", "zat6 neoi5/zai2 (niece/nephew)", "caat3 ngaa4 (brush teeth)", "so2 mun4 (lock door)", "faan1 gung1 (go to work)",
    "din6 nou5 (laptop)", "sai2 saam1 (do laundry)", "zyu2 ng5 caan1 (make lunch)", "naau6 zung1 (alarm)", "tou3 san1 hei3 (a new movie)",
    "cung1 loeng4 (take a bath)", "seoi6/fan3 gaau3 (sleep)", "hei2 san1/seng2 (wake up)", "hoi1 ci2 (begin)", "jyun4 (finish)", "maai5 sung3 (buy groceries)",
    "cung1 din6 hei3 (charger)", "lam2 (to think)", "ziu1 zou2 (morning)", "sik1 (turn off)", "cong4 (bed)", "lok6 (go down)"
    ],
    characters9: ["zik6 heoi3 (go)", "paau2 bou6 (running)", "zi1 dou3 (know)", "zi6 gei2 (yourself)", "seoi1 jiu3 (need)", "naa4 (take)", 
    "syut3 (speak)", "dang2 (wait)", "waan2 (play)", "cyun4 zoi6 (exist)", "daa2 (call)", "dung2 si6 (understanding)", "ceoi2 siu1 (cancel)", 
    "wui6 ji5 (meeting)", "dou3 daat6 (arrive)", "gung1 jyun2 (park)", "jau1 sik1 (rest)", "wui4 gaa1 (return)", "maan5 soeng6 (evening)",
    "cyu4 fong2 (kitchen)", "gam2 gok3 (feel)", "waat6 waa2 (draw)", "wui4 daap3 (answer)", "duk6 (read)", "bou3 zi2 (newspaper)", "gaau3 (teach)",
    "gei3 dak1 (remember)", "muk6 juk6 (shower)", "siu3 (laugth)", "cit3/zin2 (cut)", "dou1 (knife)", "gai3 waak6 (plan)", "nang4 (can)",
    "gaai2 sik 1 (explain)", "gwaan1 (close)", "sing4 (ride)", "zaam6 (stand)", "leoi5 hang (vacation)", "fai3 lok6 (happy)"/*, "han6 fuk1 (happiness)",
    "bei1 soeng1 (sad)", "nau1 (angry)", "laang zing6 (calm)" */],
    characters10: ["jin4 hau6 (then)", "zaa1 ce1 (drive a car)", "gu3 haak3 (customer)","caan teng1 (restaurant)", "tou5 ngo6 (hungry)",
    "jyu6 dou3 (to meet)", "king1 gai2 (talkS)", "jat1 ci3 (once)", "gwok3 kei4 (flag)", "laam4 (blue)", "soeng6 min6 (above)", "lap1 sing1 (stars)",
    "zau1 (state)", "doi6 biu2 (to represent)", "zeoi3 zou2 (earliest)", "tiu4 waan2 tiu2 (stripes)", "zau6 (precisely)", "gaa1 (add)"]
}
